version: '3.8'

services:
  postgresdb:
    image: postgres: lastest
    environment:
      - POSTGRES_PASSWORD=cayo
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - postgresVolume:/var/lib/postgres
      - postgresConfig:/etc/postgres
  
  docker-python:
    build: 
      context: .
    ports:
    - 5432:5432
    depends_on:
      - postgresdb

volumes:
  postgresVolume:
  postgresConfig:
  